### PR TITLE
fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with gcc 4.8:

```
sslh-select.c: In function 'udp_timeouts':
sslh-select.c:480:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < fd_info->max_fd; i++) {
     ^
```

Fixes:
 - http://autobuild.buildroot.org/results/4315321fb1b6c6849ff583999557106fb97b3ab7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by yrutschle** [comment]
I think gcc-4.8  supports C99? Maybe with explicit -std=c99 in CFLAGS?

**Comment by ffontaine** [comment]
`-std=gnu99` will indeed fix the build however `-std=c99` will raise the following build failure:

```
In file included from sslh-select.c:35:0:
common.h:135:25: error: 'NI_MAXHOST' undeclared here (not in a function)
 #define MAX_NAMELENGTH (NI_MAXHOST + NI_MAXSERV + 1)
                         ^
common.h:137:15: note: in expansion of macro 'MAX_NAMELENGTH'
     char peer[MAX_NAMELENGTH], service[MAX_NAMELENGTH],
               ^
common.h:135:38: error: 'NI_MAXSERV' undeclared here (not in a function)
 #define MAX_NAMELENGTH (NI_MAXHOST + NI_MAXSERV + 1)
                                      ^
common.h:137:15: note: in expansion of macro 'MAX_NAMELENGTH'
     char peer[MAX_NAMELENGTH], service[MAX_NAMELENGTH],
               ^
common.h:152:49: warning: 'struct addrinfo' declared inside parameter list [enabled by default]
 char* sprintaddr(char* buf, size_t size, struct addrinfo *a);
                                                 ^
common.h:152:49: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
common.h:153:26: warning: 'struct addrinfo' declared inside parameter list [enabled by default]
 void resolve_name(struct addrinfo **out, char* fullname);
                          ^
common.h:165:31: warning: 'struct addrinfo' declared inside parameter list [enabled by default]
 int resolve_split_name(struct addrinfo **out, char* hostname, char* port);
                               ^
sslh-select.c:54:5: error: unknown type name 'fd_set'
     fd_set fds_r, fds_w;  /* reference fd sets (used to init working copies) */
     ^
sslh-select.c: In function 'tidy_connection':
sslh-select.c:65:5: error: unknown type name 'fd_set'
     fd_set* fds = &fd_info->fds_r;
     ^
sslh-select.c:66:5: error: unknown type name 'fd_set'
     fd_set* fds2 = &fd_info->fds_w;
     ^
sslh-select.c:73:13: warning: implicit declaration of function 'FD_CLR' [-Wimplicit-function-declaration]
             FD_CLR(cnx->q[i].fd, fds);
             ^
sslh-select.c: In function 'fd_is_in_range':
sslh-select.c:87:15: error: 'FD_SETSIZE' undeclared (first use in this function)
     if (fd >= FD_SETSIZE) {
               ^
sslh-select.c:87:15: note: each undeclared identifier is reported only once for each function it appears in
sslh-select.c: In function 'connect_queue':
sslh-select.c:139:13: warning: implicit declaration of function 'FD_SET' [-Wimplicit-function-declaration]
             FD_SET(q->fd, &fd_info->fds_w);
             ^
sslh-select.c: In function 'shovel_single':
sslh-select.c:185:4: error: unknown type name 'fd_set'
    fd_set fds_r, fds_w;
    ^
sslh-select.c:189:4: warning: implicit declaration of function 'FD_ZERO' [-Wimplicit-function-declaration]
    FD_ZERO(&fds_r);
    ^
sslh-select.c:202:7: warning: implicit declaration of function 'select' [-Wimplicit-function-declaration]
       res = select(
       ^
sslh-select.c:212:11: warning: implicit declaration of function 'FD_ISSET' [-Wimplicit-function-declaration]
           if (FD_ISSET(cnx->q[i].fd, &fds_w)) {
           ^
sslh-select.c: In function 'main_loop':
sslh-select.c:523:5: error: unknown type name 'fd_set'
     fd_set readfds, writefds; /* working read and write fd sets */
     ^
sslh-select.c:524:20: error: storage size of 'tv' isn't known
     struct timeval tv;
                    ^
make[1]: *** [Makefile:68 : sslh-select.o] Erreur 1
make[1]: *** Attente des tâches non terminées....
echosrv-conf.c: In function 'myconfig_setting_lookup_stringcpy':
echosrv-conf.c:229:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(value, "%s", str);
                 ^
echosrv-conf.c: In function 'c2s_parse_file':
echosrv-conf.c:1114:20: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
            asprintf(errmsg, "%s:%d:%s", 
                    ^
echosrv-conf.c:1120:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(errmsg, "%s:%s", filename, config_error_text(c));
                 ^
echosrv-conf.c: In function 'read_block':
echosrv-conf.c:825:21: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
             asprintf(errmsg, "Mandatory option \"%s\" not found", desc->name);
                     ^
echosrv-conf.c: In function 'read_block_setval':
echosrv-conf.c:768:25: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
                 asprintf(errmsg, "Option \"%s\" wrong type, expected %s\n", 
                         ^
echosrv-conf.c: In function 'settingcpy':
echosrv-conf.c:313:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(&str, "%s", config_setting_get_string(setting));
                 ^
echosrv-conf.c: In function 'clcpy':
echosrv-conf.c:356:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(&str, "%s", (*(struct arg_str**)cl_arg)->sval[0]);
                 ^
echosrv-conf.c: In function 'regcompmatch_posix':
echosrv-conf.c:983:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(errmsg, "compiling pattern /%s/:%s", arg->regex, regerr);
                 ^
echosrv-conf.c:989:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(errmsg, "--%s %s: Illegal argument", 
                 ^
echosrv-conf.c: In function 'cfg_as_string':
echosrv-conf.c:1175:21: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
             asprintf(&subpath, "%s[%d]%s", path, config_setting_index(child), name);
                     ^
echosrv-conf.c:1177:21: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
             asprintf(&subpath, "%s/%s", path, name);
                     ^
echosrv-conf.c:1185:25: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
                 asprintf(&old, "%s", *strp);
                         ^
echosrv-conf.c:1188:25: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
                 asprintf(&old, "%s", "");
                         ^
echosrv-conf.c:1190:21: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
             asprintf(strp, "%s%s:%s", old, subpath, value);
                     ^
echosrv-conf.c: In function 'scalar_to_string':
echosrv-conf.c:1131:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(strp, "%d\n", config_setting_get_int(s));
                 ^
echosrv-conf.c:1135:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(strp, "%s\n", config_setting_get_bool(s) ?  "[true]" : "[false]" );
                 ^
echosrv-conf.c:1139:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(strp, "%lld\n", config_setting_get_int64(s));
                 ^
echosrv-conf.c:1143:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(strp, "%lf\n", config_setting_get_float(s));
                 ^
echosrv-conf.c:1147:17: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
         asprintf(strp, "%s\n", config_setting_get_string(s));
                 ^
```

**Comment by yrutschle** [comment]
that's "interesting". I suppose the required headers have changed in the standards.. or... something.

I'll look into it, but not as matter of emergency :-)
