### ISSUE TITLE
Make error with common.h and 'msg_system_error' on v1.22

### ISSUE THREAD

**Issue by SGNoc** [yrutschle/sslh#308]
I'm working on upgrading from 1.21 to 1.22. I downloaded your lastest master.zip, and edit the Makefile to enable the options:

`ENABLE_REGEX=1  # Enable regex probes`
`USELIBCONFIG=1  # Use libconfig? (necessary to use configuration files)`
`USELIBWRAP?=1   # Use libwrap?`
`USELIBCAP=1     # Use libcap?`
`USESYSTEMD=1     # Make use of systemd socket activation`
`USELIBBSD?=1     # Use libbsd (needed to update process name in `ps`)`
`COV_TEST=       # Perform test coverage?`
`PREFIX?=/usr`
`BINDIR?=$(PREFIX)/sbin`
`MANDIR?=$(PREFIX)/share/man/man8`

When I compile with 'make' I get the following errors for every location of msg_system_error:

`common.h:56:23: error: ‘msg_system_error’ undeclared (first use in this function); did you mean ‘gai_strerror’?
         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \`

There are a few more errors for the other locations containing 'msg_system_error'.

From v1.21 to v1.22 I added the package libpcre2-dev for PCRE2 support, am I missing another dependency that would get this to compile correctly? Otherwise, I haven't figured out why this isn't compiling without errors. Thanks!

**Comment by licaon-kter** [comment]
Which OS, version?

**Comment by yrutschle** [comment]
That's not 1.22, `print_message` was introduced later, in HEAD. Doesn't matter, it should still build.

`msg_system_error` is declared in `log.h`, which is not included in `common.h`, yet necessary. I have no idea how it builds on my system.

**Comment by yrutschle** [comment]
Let me know if this doesn't work you. Out of curiosity, what compiler are you using? I'm guessing there is a difference in how the macros are evaluated. Actually I do have an idea of how it builds for me: the macros are not used before after `log.h` is included, so when they get expanded, `msg_system_error` is in fact defined.

**Comment by SGNoc** [comment]
Thanks for the help, and sorry for the incorrect version. I was going on the latest number in the Changelog, but I'm using the latest pull from the master.zip. 

I'm running this on a raspberry pi: 

`Linux 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux`
```
cc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I pulled your update and am getting further in the compile process, but here is the next error (systemd-sslh-generator.c):

```
/usr/bin/ld: systemd-sslh-generator.o: in function `resolve_listen':
/usr/src/sslh-master/systemd-sslh-generator.c:12: undefined reference to `print_message'
/usr/bin/ld: /usr/src/sslh-master/systemd-sslh-generator.c:19: undefined reference to `msg_system_error'
/usr/bin/ld: systemd-sslh-generator.o: in function `get_listen_from_conf':
/usr/src/sslh-master/systemd-sslh-generator.c:46: undefined reference to `print_message'
/usr/bin/ld: /usr/src/sslh-master/systemd-sslh-generator.c:57: undefined reference to `print_message'
/usr/bin/ld: /usr/src/sslh-master/systemd-sslh-generator.c:66: undefined reference to `msg_system_error'
/usr/bin/ld: systemd-sslh-generator.o: in function `gen_sslh_config':
/usr/src/sslh-master/systemd-sslh-generator.c:122: undefined reference to `print_message'
/usr/bin/ld: /usr/src/sslh-master/systemd-sslh-generator.c:130: undefined reference to `msg_system_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:89: systemd-sslh-generator] Error 1
```

**Comment by yrutschle** [comment]
oh right, it's the build of systemd-sslh-generator that's broken, not sslh.
I need to look more into it.

**Comment by yrutschle** [comment]
ok that was easier than I feared. Please post the results :)

**Comment by SGNoc** [comment]
Ok, that did it. I was able to make and install and have sslh running again. Thanks!
