### ISSUE TITLE
Failing to build on linker error - `undefined reference to config_setting_lookup`

### ISSUE THREAD

**Issue by phandox** [yrutschle/sslh#256]
Hi,

I am building the sslh on Centos 7 and the Makefile fails on linker error, that it can't find reference to `config_setting_lookup` function:
```
make
./genver.sh >version.h
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c sslh-conf.c
sslh-conf.c: In function ‘config_setting_lookup_ud’:
sslh-conf.c:1022:5: warning: implicit declaration of function ‘config_setting_lookup’ [-Wimplicit-function-declaration]
     setting = config_setting_lookup(cfg, name);
     ^
sslh-conf.c:1022:13: warning: assignment makes pointer from integer without a cast [enabled by default]
     setting = config_setting_lookup(cfg, name);
             ^
sslh-conf.c:1027:13: warning: assignment makes pointer from integer without a cast [enabled by default]
     setting = config_setting_lookup(cfg, name);
             ^
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c common.c
common.c: In function ‘check_access_rights’:
common.c:684:5: warning: passing argument 1 of ‘hosts_ctl’ discards ‘const’ qualifier from pointer target type [enabled by default]
     if (!hosts_ctl(service, host, addr_str, STRING_UNKNOWN)) {
     ^
In file included from common.c:45:0:
/usr/include/tcpd.h:200:12: note: expected ‘char *’ but argument is of type ‘const char *’
 extern int hosts_ctl(char *daemon, char *client_name, char *client_addr, 
            ^
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c sslh-main.c
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c probe.c
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c tls.c
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c argtable3.c
cc -Wall -g -std=gnu99  -DLIBWRAP -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -DLIBBSD -c sslh-fork.c
cc -Wall -g -std=gnu99   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lwrap -lpcreposix -lconfig -lbsd
sslh-conf.o: In function `config_setting_lookup_ud':
/root/sslh/sslh-conf.c:1022: undefined reference to `config_setting_lookup'
/root/sslh/sslh-conf.c:1027: undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
make: *** [sslh-fork] Error 1

```

I've tried looking into code but I can't find any function defined for `config_setting_lookup` the call happens in `config_setting_lookup_ud` so I kinda understand that it complains about calling function without definition but maybe I just got the code wrong.

**Info about environment:**
CentOS Linux release 7.7.1908 (Core)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
GNU Make 3.82
conf2struct v1.1 (I've also tried 1.0 and master HEAD from repository)
installed libraries:
```
Name        : libbsd-devel
Arch        : x86_64
Version     : 0.8.3
Release     : 1.el7
Repo        : installed

Name        : libconfig-devel
Arch        : x86_64
Version     : 1.4.9
Release     : 5.el7
Repo        : installed

Name        : pcre-devel
Arch        : x86_64
Version     : 8.32
Release     : 17.el7
Repo        : installed

Name        : tcp_wrappers-devel
Arch        : x86_64
Version     : 7.6
Release     : 77.el7
Repo        : installed
```

Is there something that should be fixed or am I doing something wrong?
Thanks!

**Comment by phandox** [comment]
I've used upstream instead of released version. On the released it works without issues, so I am closing this.

**Comment by yrutschle** [comment]
Ok...
`config_setting_lookup` is provided by `libconfig`, so I guess there is some configuration mismatch.

**Comment by licaon-kter** [comment]
Seeing the same on CentOS 6.10 after https://github.com/yrutschle/sslh/commit/9d1d9f850a15575c40b072dd9d2413ce5ba5ec59

Note that I can build v1.20 and I can't build any of the commits that need conf2struct (perl exit 255), but on master it first fails with
```
sslh-conf.c: In function ‘sslhcfg_protocols_fprint’:
sslh-conf.c:1549: error: ‘for’ loop initial declarations are only allowed in C99 mode
sslh-conf.c:1549: note: use option -std=c99 or -std=gnu99 to compile your code
sslh-conf.c:1555: error: redefinition of ‘i’
sslh-conf.c:1549: note: previous definition of ‘i’ was here
sslh-conf.c:1555: error: ‘for’ loop initial declarations are only allowed in C99 mode
sslh-conf.c:1561: error: redefinition of ‘i’
sslh-conf.c:1555: note: previous definition of ‘i’ was here
sslh-conf.c:1561: error: ‘for’ loop initial declarations are only allowed in C99 mode
sslh-conf.c: In function ‘sslhcfg_fprint’:
sslh-conf.c:1635: error: ‘for’ loop initial declarations are only allowed in C99 mode
sslh-conf.c:1641: error: redefinition of ‘i’
sslh-conf.c:1635: note: previous definition of ‘i’ was here
sslh-conf.c:1641: error: ‘for’ loop initial declarations are only allowed in C99 mode
```
...but after I add `int i;` and remove them from `for(int i;)` as the error says I then get it to fail with:
```
./genver.sh >version.h
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
sslh-conf.c: In function ‘config_setting_lookup_ud’:
sslh-conf.c:1022: warning: implicit declaration of function ‘config_setting_lookup’
sslh-conf.c:1022: warning: assignment makes pointer from integer without a cast
sslh-conf.c:1027: warning: assignment makes pointer from integer without a cast
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c common.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-main.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c probe.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c tls.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c argtable3.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-fork.c
cc -Wall -g   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
sslh-conf.o: In function `config_setting_lookup_ud':
/root/sslh/sslh-conf.c:1022: undefined reference to `config_setting_lookup'
/root/sslh/sslh-conf.c:1027: undefined reference to `config_setting_lookup'
collect2: ld returned 1 exit status
make: *** [sslh-fork] Error 1
```

I have libconfig v1.3.2 so maybe this is too old?

**Comment by yrutschle** [comment]
Ok, the first part is `conf2struct` using C99 constructs and GCC not having a flag for that. I'll think about whether I fix c2s or sslh :-)

For the second part, I can only guess it's version problem, but I'm a bit surprised as `sslh` has been using this API for years... FWIW I'm developing on Debian which has libconfig 1.5.

**Comment by yrutschle** [comment]
FYI I pushed a change in conf2struct so it no longer uses the C99 construct.

For the missing symbol, you can try finding which version of libconfig sslh uses, and which symbols are in it:
```
$ ldd sslh-select
        libpcreposix.so.3 => /usr/lib/arm-linux-gnueabihf/libpcreposix.so.3 (0xb6ee2000)
        libconfig.so.9 => /usr/lib/arm-linux-gnueabihf/libconfig.so.9 (0xb6eca000)
 [...]
$ nm -gD /usr/lib/arm-linux-gnueabihf/libconfig.so.9
[...]
00003374 T config_setting_lookup
[...]
```
If it's not present, you'll need to find why (old version?). If it's present, well, we have an interesting linking problem to investigate :-)

**Comment by kirchwitz** [comment]
sslh-v1.21b fails to compile on CentOS 6 and CentOS 7 with and without libconfig.


Without libconfig:
**make PREFIX="/usr/local" USELIBCONFIG=""**
Fails immediately when compiling sslh-conf.c because there's no libconfig.h (sslh-conf.c didn't exist in previous versions, so it worked fine without libconfig headers installed on system).

Okay, installed libconfig-devel  (contains libconfig.h) to get beyond that, but then it gets even worse. Looks like disabling libconfig no longer works in sslh-v1.21b.

Do I need libconfig support? Worked fine without it so far. Is there a chance to make USELIBCONFIG="" work again? 


With libconfig:
**make PREFIX="/usr/local"**
Less error messages but still not compiling:

_./genver.sh >version.h
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
sslh-conf.c: In function ‘config_setting_lookup_ud’:
sslh-conf.c:1063:5: warning: implicit declaration of function ‘config_setting_lookup’ [-Wimplicit-function-declaration]
     setting = config_setting_lookup(cfg, name);
     ^
sslh-conf.c:1063:13: warning: assignment makes pointer from integer without a cast [enabled by default]
     setting = config_setting_lookup(cfg, name);
             ^
sslh-conf.c:1068:13: warning: assignment makes pointer from integer without a cast [enabled by default]
     setting = config_setting_lookup(cfg, name);
             ^
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c common.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-main.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c probe.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c tls.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c argtable3.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-fork.c
cc -Wall -g   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
sslh-conf.o: In function `config_setting_lookup_ud':
/usr/local/src/sslh-v1.21b/sslh-conf.c:1063: undefined reference to `config_setting_lookup'
/usr/local/src/sslh-v1.21b/sslh-conf.c:1068: undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
make: *** [sslh-fork] Error 1_

CentOS 6: libconfig 1.3.2
CentOS 7: libconfig 1.4.9

In libconfig version 1.5 **config_lookup_from** was renamed **config_setting_lookup**. I was curious and added this at the beginning of sslh-fork.c:

**#define config_setting_lookup config_lookup_from**

Well, seems to compile fine now, but I don't know if there were more changes in libconfig internally, or maybe it's really just that simple to fix it.

However, sslh should also compile without libconfig at all (like previous versions).

If you need more details please let me know and I'll happily try to provide missing information. Currently, I'm back to sslh 1.20 (without libconfig) to be on the safe side.

**Comment by yrutschle** [comment]
Thanks for the very clear report.

Ok, that's really two issuse :-) : 
* Missing symbol: I develop against libconfig 1.5; I don't think I have ever seen config_lookup_from, so that must be an ooooold version...
* Dependency to libconfig: oops, I didn't think to keep it optionnal. I'll have a look, and I guess I'm in for a third 1.21 release -_-

**Comment by yrutschle** [comment]
Libconfig should be optional again in 2c93a015ea1d261a934df00285691522e6a6d211.

I don't really plan to support libconfig < 1.5, which is 5 years old and 2 major versions behind...

**Comment by kirchwitz** [comment]
Just a friendly additional comment:

CentOS 7 (Red Hat Enterprise Linux 7) is by far the most widespread version in the RHEL/CentOS universe. CentOS 7 is nowhere near the end of its life-cycle. It ships with libconfig 1.4.9 and that's not going to change. (Even CentOS 6 = RHEL 6 is still supported, but let's keep it simple. :-) Yes, there is CentOS/RHEL 8 but that's still pretty new. (RHEL/CentOS people think in somewhat longer time frames, even longer than Debian people. It's a strange world.)

If a simple define statement (see my previous comment) might do the trick, it's a "cheap" way to support that large user base even with their older version of libconfig. By the way, I found that workaround on a Debian mailing list where somebody had the same problem with it's older Debian version, and he seemed to be happy with that workaround.

"sslh" is for servers, and they usually have pretty old stuff included. It's the way it is. That's not a perfect world for developers, I agree.

As you may have noticed, I don't need libconfig support myself, I'm happy without it, "sslh" works absolutely great here.

I just wanted to give it a thought for those who might need it (with libconfig) and don't use Debian (which is great Linux distribution) but for whatever reason are in the world of RedHat/CentOS. I will not bother you any further. Keep up the great work!

**Comment by yrutschle** [comment]
Fair enough.
I see there are version headers in libconfig.h, so it should be easy enough.

**Comment by yrutschle** [comment]
Follwing in #275.

**Comment by licaon-kter** [comment]
Still on CeonOS6, HEAD (8b6e06e6c76e6d92e7eecea6b82c9f0c36cecbe6)

Edit `Makefile`, set `USELIBCONFIG=0`, `make clean`, but `make` fails:
```
./genver.sh >version.h
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
sslh-conf.c: In function ‘config_setting_lookup_ud’:
sslh-conf.c:1140: warning: implicit declaration of function ‘config_setting_lookup’
sslh-conf.c:1140: warning: assignment makes pointer from integer without a cast
sslh-conf.c:1145: warning: assignment makes pointer from integer without a cast
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c common.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-main.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c probe.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c tls.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c argtable3.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-fork.c
cc -Wall -g   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
sslh-conf.o: In function `config_setting_lookup_ud':
/root/sslh/sslh-conf.c:1140: undefined reference to `config_setting_lookup'
/root/sslh/sslh-conf.c:1145: undefined reference to `config_setting_lookup'
collect2: ld returned 1 exit status
make: *** [sslh-fork] Error 1
```

Fixed by removing these 4 lines: https://github.com/yrutschle/sslh/blob/master/Makefile#L49

**Comment by yrutschle** [comment]
It's:
```
USELIBCONFIG=
```
Notice the total and complete absence of anything after the equal!

**Comment by yrutschle** [comment]
(This is not the first time this tricks someone. Ideally I'd prefer to have standard settings, I've never had time to dig into Make enough to find out how. )

**Comment by licaon-kter** [comment]
So with `1` is ON but `nothing` is OFF? That's...ok...will test :-|

**Comment by yrutschle** [comment]
I know, I know... Like I said, if someone tells me how to do it better, I'll take anything -_-'

You can do simple setups on the command line, typically:
```
sslh-select --listen myhost:443 --tls localhost:443 --ssh localhost:22
```

As soon as things get more complicated, I'd suggest using the config file...
