### ISSUE TITLE
Add compatibility implmementation of memmem

### ISSUE THREAD

**Issue by ryandesign** [yrutschle/sslh#278]
Hi, I'm a MacPorts developer, and I wanted to let you know that sslh 1.21c does not build on Mac OS X 10.6 or earlier. The error is:

```
Undefined symbols for architecture x86_64:
  "_memmem", referenced from:
      _is_xmpp_protocol in probe.o
      _is_http_protocol in probe.o
ld: symbol(s) not found for architecture x86_64
```

`memmem` was not available until Mac OS X 10.7.

This problem was [mentioned on the mailing list](http://rutschle.net/pipermail/sslh/2014-March/000501.html) but I didn't find a resolution of the thread so it may have been forgotten.

There was a suggestion in that thread to use the `memmem` compatibility implementation [available in gnulib](http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/memmem.c).

Admittedly Mac OS X 10.6 is old. If sslh doesn't wish to add compatibility code to accommodate systems so old that they don't have built-in `memmem` implementations, that's understandable.
